# Generated by Django 4.0.6 on 2022-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('fee_1_not', models.CharField(default='14999/-', max_length=10)),
                ('course_fee_01', models.CharField(max_length=10)),
                ('fee_3_not', models.CharField(default='24999/-', max_length=10)),
                ('course_fee_03', models.CharField(max_length=10)),
                ('fee_6_not', models.CharField(default='34999/-', max_length=10)),
                ('course_fee_06', models.CharField(max_length=10)),
                ('course_cont', models.TextField(blank=True, null=True)),
                ('course_heading_01', models.CharField(blank=True, max_length=100, null=True)),
                ('course_desc_01', models.TextField()),
                ('course_heading_02', models.CharField(blank=True, max_length=100, null=True)),
                ('course_desc_02', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('git_img', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
