# Generated by Django 4.0.6 on 2022-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(max_length=100)),
                ('cert_number', models.CharField(max_length=20, unique=True)),
                ('cert_created', models.DateTimeField(auto_now_add=True)),
                ('gdrive_id', models.CharField(blank=True, default='1O0EVKgJOKO_Y4MYlz_eKuufdbcSKFsO7', max_length=50, null=True)),
            ],
        ),
    ]
